name: Release artifacts
on:
  push:
    tags:
      - v*

jobs:
  build_linux_android:
    name: Build Linux + Android
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Install pre-requisites
        run: |
          cargo install cargo-ndk
          rustup target add armv7-linux-androideabi aarch64-linux-android i686-linux-android x86_64-linux-android

      - name: Build Android
        run: |
          cargo ndk --target aarch64-linux-android --platform 21 -- build --release
          cargo ndk --target armv7-linux-androideabi --platform 19 -- build --release
          cargo ndk --target i686-linux-android --platform 19 -- build --release
          cargo ndk --target x86_64-linux-android --platform 21 -- build --release
          find ./target -name libzkgroup.so | xargs zip libzkgroup-android.zip
        env:
          RUSTFLAGS: -C link-arg=-s
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk/
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk-bundle/
        
      - name: Build Linux
        working-directory: ffi/node
        run: make libzkgroup

      - name: Upload Android
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libzkgroup-android.zip
          asset_name: libzkgroup-android.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Linux
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup.so
          asset_name: libzkgroup.so
          tag: ${{ github.ref }}
          overwrite: true

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Build
        working-directory: ffi/node
        run: |
          rustup target add i686-pc-windows-msvc
          rustup target add aarch64-pc-windows-msvc
          make libzkgroup

      - name: Upload x86
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup_x86.dll
          asset_name: libzkgroup_x86.dll
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload x64
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup_x64.dll
          asset_name: libzkgroup_x64.dll
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload arm64
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup_arm64.dll
          asset_name: libzkgroup_arm64.dll
          tag: ${{ github.ref }}
          overwrite: true

  build_macOS_iOS:
    name: Build macOS + iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure git to use HTTPS
        run: git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com".insteadOf ssh://git@github.com

      - name: Install pre-requisites
        run: |
          rustup target add aarch64-apple-ios x86_64-apple-ios armv7-apple-ios armv7s-apple-ios
          cd ffi/swift
          make install_build_dependencies

      - name: Build
        run: |
          cd ffi/node
          make libzkgroup
          cd ../../ffi/swift
          make
          cd ZKGroup
          zip -r libzkgroup-ios.zip libzkgroup
      
      - name: Upload macOS
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/node/libzkgroup.dylib
          asset_name: libzkgroup.dylib
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload iOS
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ffi/swift/ZKGroup/libzkgroup-ios.zip
          asset_name: libzkgroup-ios.zip
          tag: ${{ github.ref }}
          overwrite: true
