name: Code Formatting

on:
  push:
    branches: [master]
  pull_request:

jobs:

  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run rustfmt
        run: |
          rustup toolchain install ${{ env.NIGHTLY_VERSION }}
          rustup component add rustfmt --toolchain ${{ env.NIGHTLY_VERSION }}
          cargo +${{ env.NIGHTLY_VERSION }} fmt -- --check
        env:
          NIGHTLY_VERSION: nightly-2020-04-12
